# Generated by Django 4.2.20 on 2025-04-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_system', models.CharField(max_length=100)),
                ('planet', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('solar_system', 'planet', 'country', 'address')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_velocity_mph', models.FloatField()),
                ('wind_direction', models.CharField(max_length=5)),
                ('precipitation_chance', models.FloatField()),
                ('precipitation_kind', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_time', models.DateTimeField()),
                ('weight_kg', models.FloatField()),
                ('volume_m3', models.FloatField()),
                ('eta_min', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_shipments', to='shipments.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_shipments', to='shipments.location')),
                ('weather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.weatherforecast')),
            ],
        ),
    ]
